site_name: "Pulsar Processing: MeerKAT documentation"
site_url: https://ozgrav.github.io/meerkat_pulsar_docs/
theme: readthedocs
nav:
    - Home: index.md
    - OzStar: ozstar.md
    - Software Installation: software_installation.md
    - Command examples: command_examples.md
    - MeerKAT Pulsar Processing Summary: meerkat_pulsar_summary.md
    - MeerPipe: meerpipe.md
    - OzSTAR storage: ozstar_storage.md
    - MeerTime Ephemerides and Templates: ephem_template.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
