site_name: "Pulsar Processing: MeerKAT documentation"
site_url: https://example.com/
theme: readthedocs
nav:
    - Home: index.md
    - OzStar: ozstar.md
    - Software Installation: software_installation.md
    - MeerTime Ephemerides and Templates: ephem_template.md
    - Command examples: command_examples.md
